library(sqldf)
library(stringr)
Nummerspalte <- read.csv2("Zahlenspalte.csv")
Laenge <- str_length(z)
Selektion <- paste0('SELECT Nummer FROM Nummerspalte WHERE Nummer <= ',Laenge)
Ergebnis <- sqldf(Selektion)
Ergebnis$Formeltext <- z
Ergebnis$Substr <- substr(Ergebnis$Formeltext, Ergebnis$Nummer, Ergebnis$Nummer)
Klammerzuordnung <- read.csv2("Klammerzuordnung.csv")
Test <- sqldf(" SELECT Nummer, Formeltext, Substr, Wert FROM Ergebnis LEFT JOIN Klammerzuordnung ON Ergebnis.Substr = Klammerzuordnung.Klammer ")
Join2 <- sqldf(" SELECT Nummer, Formeltext, Substr FROM Test ")